os: linux
dist: trusty
sudo: false
language: node

cache:
  - yarn

jobs:
  include:
    # Core
    - script:
        - cd core/
        - yarn install
        - yarn run test

    # Native
    - script:
        - cd native/
        - yarn install
        - yarn run test
